default:
    trainer: ppo
    beta: 5.0e-3
    epsilon: 0.2
    lambd: 0.95
    learning_rate: 3.0e-4
    memory_size: 256
    sequence_length: 64
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128
    normalize: true
    num_epoch: 3
    time_horizon: 1000
    batch_size: 2024
    buffer_size: 20240
    gamma: 0.995

CrawlerDynamicLearning:
    max_steps: 2500000
    summary_freq: 3000
    num_layers: 7
    hidden_units: 512